[project]
name = "pyqt-roi-editor"
version = "0.1"
description = "A simple ROI (region of interest) editor written in PySide6"
readme = "README.rst"
authors = [
  { name = "Rocky☆Star", email = "rocky-star22@outlook.com" }
]
requires-python = ">= 3.12"
dependencies = [
  "pyside6 >= 6.11.2",
]

[project.scripts]
pyqt-roi-editor = "pyqt_roi_editor.main:main"

[tool.pyrefly.errors]
missing-source = "ignore"
missing-source-for-stubs = "ignore"
bad-override-mutable-attribute = "error"

[build-system]
requires = [ "uv_build >= 0.12.17, < 0.13.0" ]
build-backend = "uv_build"

[tool.pyside6-project]
files = [
  # Python modules
  "src/pyqt_roi_editor/__init__.py",
  "src/pyqt_roi_editor/main.py",
  "src/pyqt_roi_editor/document.py",
  "src/pyqt_roi_editor/storage.py",
  "src/pyqt_roi_editor/helpers.py",
  "src/pyqt_roi_editor/roi_graphics_view.py",
  "src/pyqt_roi_editor/coords_input.py",
  "src/pyqt_roi_editor/zoom_box.py",
  "src/pyqt_roi_editor/shape_props_editor.py",
  "src/pyqt_roi_editor/dump_shape_dialog.py",
  # UI files
  "src/pyqt_roi_editor/mainwindow.ui",
  "src/pyqt_roi_editor/shapepropseditor.ui",
  "src/pyqt_roi_editor/dumpshapedialog.ui",
  "src/pyqt_roi_editor/coordsinput.ui",
]

[tool.pytest.ini_options]
testpaths = [ "tests" ]

[tool.pyright]
include = [ "src" ]
enableTypeIgnoreComments = true
ignore = [ "**/ui_*.py" ]
reportMissingModuleSource = "none"
reportUnusedCallResult = "none"
reportIgnoreCommentWithoutRule = "none"
reportIncompatibleUnannotatedOverride = "error"
reportUnannotatedClassAttribute = "none"

[tool.pyrefly]
project-includes = [ "src" ]
search-path = [ "typings" ]
infer-with-first-use = false

[tool.ruff.lint.isort]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
  "pyside-feature",
]

[tool.ruff.lint.isort.sections]
pyside-feature = [ "__feature__" ]

[tool.ruff.lint.pyflakes]
allowed-unused-imports = [ "__feature__" ]

[dependency-groups]
dev = [
  "pytest>=9.1.1",
]
